controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Prefix /api for all controllers in Api folder
api_controllers:
    resource:
        path: ../src/Controller/Api/
        namespace: App\Controller\Api
    type: attribute
    prefix: /api

# Swagger UI
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# Swagger JSON
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
