services:
  database:
    image: postgres:18-alpine
    container_name: timemanager_database
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - timemanager_db_data:/var/lib/postgresql/data
    networks:
      - timemanager_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: timemanager_backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/var/www/symfony
    command: >
      sh -c "composer install --no-scripts &&
             echo '‚è≥ Waiting for database...' &&
             sleep 5 &&
             php bin/console app:reset-db -n &&
             php -S 0.0.0.0:8000 -t public"
    networks:
      - timemanager_network
    depends_on:
      - database

  adminer:
    image: adminer:latest
    container_name: timemanager_adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    networks:
      - timemanager_network
    depends_on:
      - database

  frontend:
    image: node:22-alpine
    container_name: timemanager_frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - timemanager_network
    depends_on:
      - backend

volumes:
  timemanager_db_data:

networks:
  timemanager_network:
    driver: bridge