framework:
    rate_limiter:
        login_limiter:
            policy: 'sliding_window'
            limit: 5
            interval: '15 minutes'

        api_limiter:
            policy: 'sliding_window'
            limit: 100
            interval: '1 minute'
